// This deterministic fixture is a development harness, never a production feed.
package main

import (
	"context"
	"encoding/json"
	"fmt"
	"net/url"
	"os"
	"strings"
	"time"

	"github.com/jackc/pgx/v5/pgxpool"
	"phmon/server/internal/database"
	"phmon/server/internal/players"
)

func ptr[T any](v T) *T { return &v }
func main() {
	u, err := url.Parse(os.Getenv("PLAYER_REGISTRY_SIMULATOR_DATABASE_URL"))
	if err != nil || (u.Hostname() != "127.0.0.1" && u.Hostname() != "localhost") || !strings.HasPrefix(u.Path, "/player_registry_") {
		panic("set PLAYER_REGISTRY_SIMULATOR_DATABASE_URL to a disposable loopback player_registry_* database")
	}
	ctx, cancel := context.WithTimeout(context.Background(), 30*time.Second)
	defer cancel()
	pool, err := pgxpool.New(ctx, u.String())
	if err != nil {
		panic(err)
	}
	defer pool.Close()
	if err = database.Migrate(ctx, pool); err != nil {
		panic(err)
	}
	s := players.NewStore(pool)
	server := "Fixture Browser Registry " + fmt.Sprint(time.Now().UnixNano())
	base := time.Now().Add(-time.Hour).UTC()
	batch := []players.Observation{}
	for i := 0; i < 35; i++ {
		o := players.Observation{Server: server, Name: fmt.Sprintf("FixturePlayer%02d", i), NameType: "unknown", Level: ptr(100 + i%15), Guild: ptr("Fixture Guild"), Source: "synthetic.browser-fixture", SourceRef: fmt.Sprintf("fixture-%d", i), ObservedAt: base.Add(time.Duration(i) * time.Second), SessionID: "synthetic-session", Epoch: "synthetic-epoch", RuntimeID: fmt.Sprint(i), Location: &players.Location{Region: 25000, X: float64(i), Y: 20}}
		if i%5 == 0 {
			o.NameType = "job"
			o.Job = ptr([]string{"hunter", "trader", "thief"}[(i/5)%3])
		}
		if i%3 == 0 {
			o.Equipment = &players.Equipment{Availability: "observed_partial", Source: "synthetic.browser-fixture", Profile: "synthetic-only", ObservedAt: o.ObservedAt, Slots: []players.EquipmentSlot{{Slot: "head", State: "occupied", ModelID: ptr(int64(5264)), Plus: ptr(7), Variance: ptr("18446744073709551615"), MagicOptions: map[string]string{"1": "9007199254740993"}, ObservedAt: o.ObservedAt}, {Slot: "shield", State: "empty", ObservedAt: o.ObservedAt}}}
		} else if i%3 == 1 {
			o.Equipment = &players.Equipment{Availability: "observed_complete", Source: "synthetic.browser-fixture", Profile: "synthetic-only", ObservedAt: o.ObservedAt}
			for _, slot := range players.EquipmentSlots[:12] {
				o.Equipment.Slots = append(o.Equipment.Slots, players.EquipmentSlot{Slot: slot, State: "empty", ObservedAt: o.ObservedAt})
			}
		}
		batch = append(batch, o)
	}
	if err = s.ApplyObservations(ctx, batch); err != nil {
		panic(err)
	}
	page, err := s.List(ctx, players.Filter{Server: server, Limit: 100, Sort: "name", Direction: "asc"})
	if err != nil {
		panic(err)
	}
	first, second := page.Players[0], page.Players[2]
	// A retained review candidate is generated by independently observed,
	// contradictory alias evidence, without enabling any packet decoder.
	conflict := batch[4]
	conflict.Model = ptr(int64(1907))
	conflict.SourceRef = "conflict-a"
	conflict.ObservedAt = base.Add(40 * time.Second)
	if err = s.ApplyObservations(ctx, []players.Observation{conflict}); err != nil {
		panic(err)
	}
	conflict.Model = ptr(int64(1908))
	conflict.SourceRef = "conflict-b"
	conflict.ObservedAt = base.Add(41 * time.Second)
	if err = s.ApplyObservations(ctx, []players.Observation{conflict}); err != nil {
		panic(err)
	}
	result := map[string]any{"fixture": true, "server": server, "profile_id": first.ID, "target_id": second.ID, "candidate_profile_id": page.Players[4].ID, "players": 36, "runtime_equipment_verified": false}
	_ = json.NewEncoder(os.Stdout).Encode(result)
}
